name: new_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  
  # State Management
  provider: ^6.1.1
  
  # UI & Storage
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
